name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Keep CNAME File
        run: echo "www.carlmathewgabay.top" > ./dist/CNAME

      - name: Get Current Version
        id: get_version
        run: |
          VERSION_FILE="./dist/version.txt"
          TODAY=$(date +'%m.%d.%y')
          LAST_VERSION=$(cat $VERSION_FILE)

          if [[ "$LAST_VERSION" == v$TODAY* ]]; then
              if [[ "$LAST_VERSION" =~ _r([0-9]+)$ ]]; then
                  REVISION_NUMBER=$(echo $LAST_VERSION | sed 's/.*_r\([0-9]*\)/\1/')
                  NEW_REVISION=$((REVISION_NUMBER + 1))
                  VERSION="v$TODAY"_r$NEW_REVISION
              else
                  VERSION="v$TODAY"_r1
              fi
          else
              VERSION="v$TODAY"
          fi

          echo $VERSION > $VERSION_FILE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist